[package]
name = "bakuretsu_komasute_taro_r"
version = "0.3.0"
edition = "2021"

[profile.release]
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shogi = "0.12.2"
serde_json = "1.0.59"