name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target          
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Run bakuretsu_komahiroi_taro engine fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all --manifest-path engine/bakuretsu_komahiroi_taro/Cargo.toml -- --check
    - name: Run bakuretsu_komahiroi_taro engine clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --manifest-path engine/bakuretsu_komahiroi_taro/Cargo.toml -- -D warnings
    - name: Run bakuretsu_komahiroi_taro engine tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --manifest-path engine/bakuretsu_komahiroi_taro/Cargo.toml --all-features

    - name: Run bakuretsu_komahiroi_taro train fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all --manifest-path train/bakuretsu_komahiroi_taro/Cargo.toml -- --check
    - name: Run bakuretsu_komahiroi_taro train clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --manifest-path train/bakuretsu_komahiroi_taro/Cargo.toml -- -D warnings
    - name: Run bakuretsu_komahiroi_taro train tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --manifest-path train/bakuretsu_komahiroi_taro/Cargo.toml --all-features
